export const ALL_INSTRUMENTS = {
  guitars: 'Guitarras',
  bass: 'Bajo',
  drums: 'Batería',
  vocals: 'Voces',
  keys: 'Teclados',
  winds: 'Vientos',
  strings: 'Cuerdas',
  percussion: 'Percusión',
  sfx: 'Efectos de Sonido',
  synths: 'Sintetizadores',
  samples: 'Samples',
  choir: 'Coros',
  brass: 'Metales',
  acoustic_guitar: 'Guitarra Acústica',
  electric_guitar: 'Guitarra Eléctrica',
  piano: 'Piano',
  organ: 'Órgano',
  harmonica: 'Armónica',
  flute: 'Flauta',
  violin: 'Violín',
  cello: 'Cello',
  harp: 'Arpa',
  turntables: 'Turntables / DJ',
  programming: 'Programación',
};
